[build]
  command = "npm run build"
  publish = ".svelte-kit/netlify"
  functions = "netlify/functions"
  node_bundler = "esbuild"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 5173
  publish = ".svelte-kit/netlify"
  functions = "netlify/functions"
  functionsPort = 9999 